"""criar_tabelas_vendas_e_limite_credito

Revision ID: 9bbf8fab2b64
Revises: 4143f556a13d
Create Date: 2026-07-30 12:52:23.606349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9bbf8fab2b64'
down_revision: Union[str, Sequence[str], None] = '4143f556a13d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendas',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('loja_id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=True),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=20), nullable=False),
    sa.Column('valor_total', sa.Float(), nullable=False),
    sa.Column('desconto', sa.Float(), nullable=False),
    sa.Column('data_venda', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendas_tenant_id'), 'vendas', ['tenant_id'], unique=False)
    op.create_table('itens_venda',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('venda_id', sa.Uuid(), nullable=False),
    sa.Column('produto_id', sa.Uuid(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Float(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('clientes', sa.Column('limite_credito', sa.Float(), nullable=False))
    op.add_column('clientes', sa.Column('saldo_devedor_crediario', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clientes', 'saldo_devedor_crediario')
    op.drop_column('clientes', 'limite_credito')
    op.drop_table('itens_venda')
    op.drop_index(op.f('ix_vendas_tenant_id'), table_name='vendas')
    op.drop_table('vendas')
    # ### end Alembic commands ###
