"""criar_tabela_financeiro_lancamentos

Revision ID: d8a55bfa7e37
Revises: 9bbf8fab2b64
Create Date: 2026-08-09 23:27:16.914052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8a55bfa7e37'
down_revision: Union[str, Sequence[str], None] = '9bbf8fab2b64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financeiro_lancamentos',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('loja_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(length=50), nullable=False),
    sa.Column('status_pagamento', sa.String(length=20), nullable=False),
    sa.Column('data_lancamento', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['loja_id'], ['lojas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financeiro_lancamentos_tenant_id'), 'financeiro_lancamentos', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_financeiro_lancamentos_tenant_id'), table_name='financeiro_lancamentos')
    op.drop_table('financeiro_lancamentos')
    # ### end Alembic commands ###
