"""criar tabela transferencias_estoque

Revision ID: f60703ae87f2
Revises: 808f708cc9f9
Create Date: 2026-07-27 13:04:28.073451

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f60703ae87f2'
down_revision: str | Sequence[str] | None = '808f708cc9f9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transferencias_estoque',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('loja_origem_id', sa.Uuid(), nullable=False),
    sa.Column('loja_destino_id', sa.Uuid(), nullable=False),
    sa.Column('produto_id', sa.Uuid(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('solicitado_por_id', sa.Uuid(), nullable=False),
    sa.Column('aprovado_por_id', sa.Uuid(), nullable=True),
    sa.Column('justificativa', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['aprovado_por_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['loja_destino_id'], ['lojas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['loja_origem_id'], ['lojas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['solicitado_por_id'], ['usuarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transferencias_estoque_tenant_id'), 'transferencias_estoque', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transferencias_estoque_tenant_id'), table_name='transferencias_estoque')
    op.drop_table('transferencias_estoque')
    # ### end Alembic commands ###
